spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: kyawgyi
        url: jdbc:mysql://localhost:3306/role
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: "kyawzinwinhtike6@gmail.com"
        password: "ctnm aobl yutt laak"
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true
server:
    port: 9000

project:
    poster : posters/



